name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
      - name: build sowon
        run: |
          make
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
      - name: build sowon
        run: |
          make
        env:
          CC: clang
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 pkg-config
      - name: build sowon
        run: |
          make
        env:
          CC: clang
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: download sdl2
        run: |
          curl -fsSL -o SDL2-devel-2.0.12-VC.zip https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip
          tar -xf SDL2-devel-2.0.12-VC.zip
          mv SDL2-2.0.12 SDL2
      - name: build sowon
        shell: cmd
        run: |
          ./build_msvc.bat
# TODO: FreeBSD build is broken
#  build-freebsd:
#    runs-on: macos-latest
#    name: FreeBSD LLVM Clang build
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build on FreeBSD
#        id: build
#        uses: vmactions/freebsd-vm@v0.0.9
#        with:
#          usesh: true
#          prepare: pkg install -y sdl2 pkgconf
#          run: |
#            freebsd-version
#            make
